TBS/b2b/urls.py
from django.urls import path,re_path

from .views import LendRecordListView

urlpatterns = [
	path('lend_record/list/',LendRecordListView.as_view(),name='lend_record_list'),
]

TBS/config/urls.py
from django.contrib import admin
from django.urls import include,path,re_path

from django.conf import settings
from django.conf.urls.static import static

from user.views import EmployeeLoginView,Logout,EmployeeIndexView

admin.site.site_header = "GEMYARD"
admin.site.site_title = "GEMYARD"
admin.site.index_title = "GEMYARD"

api_url_patterns = [
    path('jewelry/',include('jewelry.api.urls')),
    path('user/',include('user.api.urls')),
    path('core/',include('core.api.urls')),
    path('b2b/',include('b2b.api.urls')),
    path('b2c/',include('b2c.api.urls')),
]

urlpatterns = [
    path('',EmployeeIndexView.as_view()),
    path('login/',EmployeeLoginView.as_view()),
    path('logout/',Logout),
    path('salary', include('salary.urls')),
    path('admin/', admin.site.urls),
    path('api/',include(api_url_patterns)),
    path('jewelry/',include('jewelry.urls')),
    path('b2c/',include('b2c.urls')),
    path('b2b/',include('b2b.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TBS/b2b/models/base.py
# -*- coding: utf-8 -*-
from django.db import models
from jewelry.models import Depot,Record


#借货单
class B2BRecord(Record):
	depot = models.ForeignKey(Depot,on_delete=models.CASCADE)

class B2BConfirm(B2BRecord):
	record = models.OneToOneField(B2BRecord,on_delete=models.CASCADE,related_name='confirm')

TBS/b2c/models.py
# -*- coding: utf-8 -*-
from django.db import models
from datetime import date
from django.utils import timezone
from user.models import Person,Address,Customer,Employee
from jewelry.models import Merchandise,Depot
from computedfields.models import ComputedFieldsModel, computed

# Create your models here.

class Order(models.Model):
	'''订单.'''
	order_id = models.BigAutoField("订单号",primary_key=True)
	customer = models.ForeignKey(
		Customer,
		on_delete=models.PROTECT,
		blank=False,
		related_name = "order",
		verbose_name = "顾客",
	)

	order_date = models.DateTimeField("订单日期",default=timezone.now)
	last_change = models.DateTimeField('最后修改',default=timezone.now)
	
	other_fee = models.DecimalField("其它",default=0,max_digits = 10,decimal_places = 2)
	deduct = models.DecimalField("优惠金额",default=0,max_digits = 10,decimal_places = 2)
	total_value = models.DecimalField("总价",max_digits = 10,decimal_places = 2)

	comments = models.TextField("备注",blank = True,default = "",max_length=100)

	is_payed = models.BooleanField("付款",default = False)
	is_shiped = models.BooleanField("发货",default = False)
	is_recieved = models.BooleanField("签收",default = False)

	def __str__(self):
		return str(self.order_id)
	class Meta:
		verbose_name = "订单"
		verbose_name_plural = verbose_name

class Package(models.Model):
	ship_date = models.DateTimeField("发货日期",null = True,blank = True)
	sign_date = models.DateTimeField("签收日期",null=True,blank = True)

	carrier = models.CharField("承运",blank=True,default="自提",max_length=20)
	track_no = models.CharField("运单号",blank = True,default = "",max_length=20)
	gross_weight = models.FloatField("毛重",default=0)

	ship_fee = models.DecimalField("运费",default=0,max_digits = 10,decimal_places = 2)
	packaging = models.DecimalField("包装费",default=0,max_digits = 10,decimal_places = 2)
	insurance = models.DecimalField("保险",default=0,max_digits = 10,decimal_places = 2)
	other_fee = models.DecimalField("其它",default=0,max_digits = 10,decimal_places = 2)

	def __str__(self):
		return "包裹"
	class Meta:
		verbose_name = "包裹"
		verbose_name_plural = verbose_name

class SalesRecord(ComputedFieldsModel):
	merchandise = models.ForeignKey(
		Merchandise,
		null = True,
		blank = False,
		on_delete=models.SET_NULL,
		related_name = "sales_record",
		verbose_name = "商品"
	)
	
	#简单记录商品信息，一旦商品删除后销售记录仍然可查询
	#description = models.CharField("商品描述",max_length=100)
	#price = models.FloatField("标价",default=0)
	@computed(models.CharField("商品描述",max_length=100), depends=[['merchandise', ['description']]])
	def description(self):
		return merchandise.description()
	@computed(models.DecimalField("标价",max_digits = 10,decimal_places = 2), depends=[['merchandise', ['price']]])
	def price(self):
		return merchandise.price()

	#销售信息
	#deduct = models.FloatField("优惠",default=0)
	actrual_price = models.DecimalField("售价",default = 0,max_digits = 10,decimal_places = 2)

	order = models.ForeignKey(
		Order,
		on_delete=models.CASCADE,
		related_name="sales_record",
		verbose_name="订单"
	)
	package = models.ForeignKey(
		Package,
		null = True,
		blank = True,
		on_delete=models.SET_NULL,
		related_name = "sales_record",
		verbose_name = "包裹"
	)

	def __str__(self):
		return "宝贝"
	class Meta:
		verbose_name = "销售记录"
		verbose_name_plural = verbose_name

class Refund(models.Model):

	date = models.DateTimeField("退货日期",default=timezone.now)
	
	customer = models.ForeignKey(
		Customer,
		null = True,
		blank = True,
		on_delete = models.SET_NULL,
		related_name = "refund_record",
		verbose_name = "顾客"
	)

	actrual_price = models.DecimalField("退款金额",default = 0,max_digits = 10,decimal_places = 2)

	def __str__(self):
		return str(self.order_id)
	class Meta:
		verbose_name = "退款"
		verbose_name_plural = verbose_name


class RefundRecord(models.Model):
	refund = models.ForeignKey(
		Refund,
		on_delete = models.CASCADE,
		blank = False,
		related_name = "refund_record",
		verbose_name = "退货申请"
	)

	sales_record = models.ForeignKey(
		SalesRecord,
		on_delete = models.CASCADE,
		blank = False,
		related_name = "refund_record",
		verbose_name = "销售记录"
	)
	
	package = models.ForeignKey(
		Package,
		null = True,
		blank = True,
		on_delete=models.SET_NULL,
		related_name = "refund_record",
		verbose_name = "包裹"
	)

	def __str__(self):
		return "退货记录"
	class Meta:
		verbose_name = "退货记录"
		verbose_name_plural = verbose_name

#销售分成
class SalesShare(models.Model):
	order = models.ForeignKey(
		Order,
		on_delete=models.CASCADE,
		related_name="sales_share",
		verbose_name="订单"
	)
	employee = models.ForeignKey(
		Employee,
		on_delete=models.CASCADE,
		related_name="sales_share",
		verbose_name="销售"
	)
	share = models.DecimalField("销售分成%",max_digits = 4,decimal_places = 1)

	def __str__(self):
		return str(self.order.order_id)+":"+str(self.share*100)+r"%"

	class Meta:
		verbose_name = "销售分成"
		verbose_name_plural = verbose_name

#支出
class Outlay(models.Model):
	pass

#维修单
class Repair(models.Model):
	pass




class Pay(models.Model):
	is_income = models.BooleanField("收入",default=True)
	PAY_TYPE = (
		("CASH","现金"),
		("BANK","银行转账"),
		("CRED","信用卡付款"),
		("WXZF","微信支付"),
		("WXZZ","微信转账"),
		("WXHB","微信红包"),
		("APZF","支付宝支付"),
		("APZZ","支付宝转账"),
		("BLCE","店内余额"),
	)
	pay_type = models.CharField("付款方式",choices=PAY_TYPE,max_length=4)
	amount = models.DecimalField("付款金额",max_digits = 10,decimal_places = 2)
	pay_time = models.DateTimeField("付款时间",default = timezone.now)

	order = models.ForeignKey(
		Order,
		null=True,
		blank = True,
		on_delete=models.SET_NULL,
		related_name="pay",
		verbose_name="订单"
	)
	refund = models.ForeignKey(
		Refund,
		null=True,
		blank = True,
		on_delete=models.SET_NULL,
		related_name="pay",
		verbose_name="退货"
	)

	img = models.ImageField("截图",blank=True)
	def __str__(self):
		return str(self.order_id)
	class Meta:
		verbose_name = "付款"
		verbose_name_plural = verbose_name	

	

TBS/b2c/models/order.py
# -*- coding: utf-8 -*-
from django.db import models
from user.models import Customer,Employee
from jewelry.models import Record

# Create your models here.

class Order(Record):
	'''订单.'''
	customer = models.ForeignKey(
		Customer,
		on_delete=models.PROTECT,
		blank=False,
		related_name = "order",
		verbose_name = "顾客",
	)

	other_fee = models.DecimalField("其它费用",default=0,max_digits = 10,decimal_places = 2)
	deduct = models.DecimalField("优惠金额",default=0,max_digits = 10,decimal_places = 2)

	#销售及分成
	employees = models.ManyToManyField(Employee,through='SalesShare')

	def is_balanced(self):
		return self.total_pays >= self.total_value+self.other_fee-self.deduct

	def can_close(self):
		if not self.is_payed or self.is_signed:
			return False
		else:
			for pay in self.pays:
				if pay.img is None:
					return False
		return True

	def __str__(self):
		return str(self.id)

	def add_merchandise(self,merchandise,package,price,comments):
		self.save()
		if merchandise:
			merchandise.save()
		MerchandiseRecord.objects.create(	order = self,
											merchandise = merchandise,
											package = package,
											price = price,
											comments = comments)

	def add_sales_share(self,employee,share):
		if(share>100):
			raise OverflowError

		total_share = 0
		for ss in self.sales_share:
			total_share += ss.share

		if(total_share+share>100):
			raise OverflowError

		self.save()
		SalesShare.objects.create(	order = self,
									employee = employee,
									share = share)


	class Meta:
		verbose_name = "订单"
		verbose_name_plural = verbose_name
		ordering = ['-id']


#销售分成
class SalesShare(models.Model):
	order = models.ForeignKey(
		Order,
		on_delete=models.CASCADE,
		related_name="sales_share",
		verbose_name="订单"
	)
	employee = models.ForeignKey(
		Employee,
		on_delete=models.CASCADE,
		related_name="sales_share",
		verbose_name="销售"
	)
	share = models.DecimalField(r"销售分成(%)",max_digits = 4,decimal_places = 1)

	def __str__(self):
		return str(self.employee)+":"+str(self.share)+r"%"

	class Meta:
		verbose_name = "销售分成"
		verbose_name_plural = verbose_name

TBS/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">


<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/fontawesome.js' %}" data-auto-replace-svg="nest"></script>

  
  <meta name="theme-color" content="#7952b3">
  <link rel="shortcut icon" href="#" />
  {%block media%}{%endblock%}
</head>
<body>
  <div class="sticky-top">
  <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <img src="/static/img/logo_white.png" alt="" width="22"  class="d-inline-block align-text-top">
        GEMYARD
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">    </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              商品
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'merchandise_list' %}">查看</a></li>
              <li><hr class="dropdown-divider"></li>

              <li><a class="dropdown-item" href="#">入库</a></li>
              <li><a class="dropdown-item" href="#">退库</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              订单
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'order_list' %}">查看</a></li>
              <li><hr class="dropdown-divider"></li>

              <li><a class="dropdown-item" href="{% url 'order_create' %}">新订单</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">包裹</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">付款</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">客户</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              合作伙伴
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'lend_record_list' %}">借货单</a></li>
              <li><a class="dropdown-item" href="#">借货确认单</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">调货单</a></li>
              <li><a class="dropdown-item" href="#">调货确认单</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">维修单</a></li>
              <li><a class="dropdown-item" href="#">维修回货单</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">拆分单</a></li>
              <li><a class="dropdown-item" href="#">组装单</a></li>
            </ul>
          </li>

        </ul>
      </div>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

      <div class="d-flex">
       <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex">
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if request.session.uid %}{{ request.session.name }}{% else %}登 录{% endif %}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/logout/">注销</a></li>
            <li><a class="dropdown-item" href="#">修改密码</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">密码登录</a></li>
          </ul>
        </li>
      </ul>
    </div>

  </nav>
{% block nav-tabs %}

{% endblock %}
 </div>


  <div class="row m-3 ">
    <div class="col-10">
      <div class=" shadow p-3 mb-5 bg-body rounded">
        {% block content %} 

        {% endblock %}
      </div>
    </div>

    <div class="col-2">
      <div class="row">
        <div class="shadow p-3 mb-5 bg-body rounded">
          {% block side1 %}
          <li>1</li>
          <li>1</li>
          <li>1</li>
          <li>1</li>
          <li>1</li>
          {% endblock %}
        </div>
      </div>

    </div>

  </div>




</body>
</html>

TBS/templates/colored_gem_list.html
{% extends "base.html" %}

{% block title %}成品列表{% endblock %}

{% block nav-tabs %}
 <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'merchandise_list' %}">所有</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'jewel_list' %}">成品</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accessory_list' %}">配件</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'pearl_list' %}">裸珠</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'diamond_list' %}">钻石</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'colored_gem_list' %}">彩宝</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'other_list' %}">其它</a>
    </li>

  </ul>
{% endblock %}

{% block content %} 


<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">缩略图</th>
      <th scope="col">#</th>
      <th scope="col">描述</th>
      <th scope="col">位置</th>
      <th scope="col">类型</th>
      <th scope="col">价格类别</th>
      <th scope="col">价格</th>
    </tr>
  </thead>
  <tbody>
    {% for merchandise in merchandises %}


    <tr valign="middle">
      <td>
        <img class="img-thumbnail rounded shadow" src='{{merchandise.img.url}}' width="70" serialId={{merchandise.serialId|upper}} description={{merchandise.description|truncatewords:"20"}}>
      </td>
      <th scope="row">{{merchandise.serialId|upper}}</th>
      <td>{{merchandise.description|truncatewords:"20"}}</td>
      <td>{{merchandise.depot}}</td>
      <td>{{merchandise.get_jewel_type_display}}</td>
      <td>{{merchandise.price_category}}</td>
      <td>{{merchandise.price}}</td>
    </tr>

    {% endfor %}
  </tbody>
</table>


<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if merchandises.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ merchandises.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="True" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}

    {% if merchandises.number|add:'-4' > 1 %}
    <li class="page-item"><a class="page-link" href="?page={{ merchandises.number|add:'-5' }}">&hellip;</a></li>
    {% endif %}

    {% for i in merchandises.paginator.page_range %}
    {% if merchandises.number == i %}
    <li class="page-item active" aria-current="page">
      <span class="page-link">
        {{ i }}
        <span class="sr-only">(current)</span>
      </span>
    </li>
    {% elif i > merchandises.number|add:'-5' and i < merchandises.number|add:'5' %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}

    {% if merchandises.paginator.num_pages > merchandises.number|add:'4' %}
    <li class="page-item"><a class="page-link" href="?page={{ merchandises.number|add:'5' }}">&hellip;</a></li>
    {% endif %}

    {% if merchandises.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ merchandises.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="True" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>



<script>
  $(".img-thumbnail").click(
    function() {
      $('.imagepreview').attr('src', $(this).attr('src'));
      $('#imagepreview_detail').html($(this).attr('serialId')+"<br>"+$(this).attr('description'))
      $('#imagemodal').modal('show'); 
    }
    )

  </script>

  <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" data-dismiss="modal">
      <div class="modal-content"  >              
        <div class="modal-body">
         <img src="" class="imagepreview" style="width: 100%;" >
       </div> 
       <div class="modal-footer">
         <div class="col-xs-12">
           <p class="text-left" id="imagepreview_detail" align="right">1. line of description<br>2. line of description <br>3. line of description</p>
         </div>
       </div>         
     </div>
   </div>
 </div>

{% endblock %}

{% block side1%}

<form method="get">

       {{ filter.form.as_p }}


      <div class="d-grid gap-2 col-8 mx-auto">
        <div class="btn-group" role="group">
          <a href="{{ request.path }}">
          <button type="button" class="btn btn-outline-primary btn-sm" >重置</button>
          </a>
          <input class="btn btn-primary btn-sm" type="submit" value="过滤" />
        </div>
      </div>
</form>


{%endblock%}

TBS/templates/jewel_list.html
{% extends "base.html" %}

{% block title %}成品列表{% endblock %}

{% block nav-tabs %}
 <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'merchandise_list' %}">所有</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'jewel_list' %}">成品</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accessory_list' %}">配件</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'pearl_list' %}">裸珠</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'diamond_list' %}">钻石</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'colored_gem_list' %}">彩宝</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'other_list' %}">其它</a>
    </li>

  </ul>
{% endblock %}

{% block content %} 


<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">缩略图</th>
      <th scope="col">#</th>
      <th scope="col">描述</th>
      <th scope="col">长度/手寸</th>
      <th scope="col">位置</th>
      <th scope="col">类型</th>
      <th scope="col">价格类别</th>
      <th scope="col">价格</th>
    </tr>
  </thead>
  <tbody>
    {% for merchandise in merchandises %}


    <tr valign="middle">
      <td>
        <img class="img-thumbnail rounded shadow" src='{{merchandise.img.url}}' width="70" serialId={{merchandise.serialId|upper}} description={{merchandise.description|truncatewords:"20"}}>
      </td>
      <th scope="row">{{merchandise.serialId|upper}}</th>
      <td>{{merchandise.description|truncatewords:"20"}}</td>
      <td>{{merchandise.size}}</td>
      <td>{{merchandise.depot}}</td>
      <td>{{merchandise.get_jewel_type_display}}</td>
      <td>{{merchandise.price_category}}</td>
      <td>{{merchandise.price}}</td>
    </tr>

    {% endfor %}
  </tbody>
</table>

{% include "paginator.html" with page_obj="merchandises" %}


<script>
  $(".img-thumbnail").click(
    function() {
      $('.imagepreview').attr('src', $(this).attr('src'));
      $('#imagepreview_detail').html($(this).attr('serialId')+"<br>"+$(this).attr('description'))
      $('#imagemodal').modal('show'); 
    }
    )

  </script>

  <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" data-dismiss="modal">
      <div class="modal-content"  >              
        <div class="modal-body">
         <img src="" class="imagepreview" style="width: 100%;" >
       </div> 
       <div class="modal-footer">
         <div class="col-xs-12">
           <p class="text-left" id="imagepreview_detail" align="right">1. line of description<br>2. line of description <br>3. line of description</p>
         </div>
       </div>         
     </div>
   </div>
 </div>

{% endblock %}

{% block side1%}

<form method="get">

       {{ filter.form.as_p }}


      <div class="d-grid gap-2 col-8 mx-auto">
        <div class="btn-group" role="group">
          <a href="{{ request.path }}">
          <button type="button" class="btn btn-outline-primary btn-sm" >重置</button>
          </a>
          <input class="btn btn-primary btn-sm" type="submit" value="过滤" />
        </div>
      </div>
</form>


{%endblock%}

TBS/templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>GEMYARD</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <meta name="theme-color" content="#7952b3">

  <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
      }
  }
</style>
<link href="{% static 'css/signin.css' %}" rel="stylesheet">
</head>
<body class="text-center">
    {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                      <strong>{{ message }}</strong>
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                  {% endfor %}
                {% endif %}
                
    <main class="form-signin">
        <form class="mt-4" action="" method="post">
            <img class="mb-4-sm" src="/static/img/logo_white.png" alt="" width="100">
            <h1 class="h3 mb-3 fw-normal">请登录</h1>
            {% csrf_token %}
            <div class="form-floating shadow-sm">
                {{form.mobile}}
                <label>{{form.mobile.label}}</label>
            </div>
            <div class="form-floating shadow-sm">
                {{form.password}}
                <label>{{form.password.label}}</label>
            </div>
            <div class="d-inline-block w-100">
                <button type="submit" class="w-100 btn btn-lg btn-primary  shadow-sm">登录</button>
            </div>
            <p class="mt-5 mb-3 text-muted">&copy; 2012–2022 GEMYARD</p>
        </form>
    </main>
</body>
</html>