TBS/b2b/urls.py
from django.urls import path,re_path

from .views import LendRecordListView

urlpatterns = [
	path('lend_record/list/',LendRecordListView.as_view(),name='lend_record_list'),
]

TBS/config/urls.py
from django.contrib import admin
from django.urls import include,path,re_path

from django.conf import settings
from django.conf.urls.static import static

from user.views import EmployeeLoginView,Logout,EmployeeIndexView

admin.site.site_header = "GEMYARD"
admin.site.site_title = "GEMYARD"
admin.site.index_title = "GEMYARD"

api_url_patterns = [
    path('jewelry/',include('jewelry.api.urls')),
    path('user/',include('user.api.urls')),
    path('core/',include('core.api.urls')),
    path('b2b/',include('b2b.api.urls')),
    path('b2c/',include('b2c.api.urls')),
]

urlpatterns = [
    path('',EmployeeIndexView.as_view()),
    path('login/',EmployeeLoginView.as_view()),
    path('logout/',Logout),
    path('salary', include('salary.urls')),
    path('admin/', admin.site.urls),
    path('api/',include(api_url_patterns)),
    path('jewelry/',include('jewelry.urls')),
    path('b2c/',include('b2c.urls')),
    path('b2b/',include('b2b.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TBS/jewelry/api/urls.py
from django.urls import path,re_path

from .views import DepotList,DepotDetail
from .views import CertificateList,CertificateDetail
from .views import PriceCategoryList,PriceCategoryDetail
from .views import RecordList,RecordDetail,MerchandiseRecordList,MerchandiseRecordDetail,RecordPayList,RecordPayDetail
from .views import SkuList,SkuDetail,MerchandiseList,MerchandiseDetail
from .views import JewelList,JewelDetail,AccessoryList,AccessoryDetail
from .views import GemList,GemDetail,PearlList,PearlDetail,DiamondList,DiamondDetail,ColoredGemList,ColoredGemDetail

'''
from django.views.decorators.http import require_http_methods
from .models import Jewel
from django.http import HttpResponse
def add_100_jewel(request):
	jewel = Jewel.objects.first()
	i = 100
	while i>0:
		jewel.pk = None
		jewel.id = None
		jewel.save()
		i-=1
			
	return HttpResponse(Jewel.objects.all().count())
'''

urlpatterns = [
#	path('add_100_jewel/',add_100_jewel),
	path('Depot/',DepotList.as_view(),name="depot_list"),
	path('Depot/<int:pk>/',DepotDetail.as_view(),name="depot_detail"),

	path('Certificate/',CertificateList.as_view(),name="Certificate_list"),
	path('Certificate/<int:pk>/',CertificateDetail.as_view(),name="Certificate_detail"),

	path('PriceCategory/',PriceCategoryList.as_view(),name="PriceCategory_list"),
	path('PriceCategory/<int:pk>/',PriceCategoryDetail.as_view(),name="PriceCategory_detail"),

	path('Record/',RecordList.as_view(),name="Record_list"),
	path('Record/<int:pk>/',RecordDetail.as_view(),name="Record_detail"),

	path('MerchandiseRecord/',MerchandiseRecordList.as_view(),name="MerchandiseRecord_list"),
	path('MerchandiseRecord/<int:pk>/',MerchandiseRecordDetail.as_view(),name="MerchandiseRecord_detail"),

	path('RecordPay/',RecordPayList.as_view(),name="RecordPay_list"),
	path('RecordPay/<int:pk>/',RecordPayDetail.as_view(),name="RecordPay_detail"),

	path('Sku/',SkuList.as_view(),name="Sku_list"),
	path('Sku/<int:pk>/',SkuDetail.as_view(),name="Sku_detail"),

	path('Merchandise/',MerchandiseList.as_view(),name="Merchandise_list"),
	path('Merchandise/<int:pk>/',MerchandiseDetail.as_view(),name="Merchandise_detail"),

	path('Merchandise/Jewel/',JewelList.as_view(),name="Jewel_list"),
	path('Merchandise/Jewel/<int:pk>/',JewelDetail.as_view(),name="Jewel_detail"),

	path('Merchandise/Accessory/',AccessoryList.as_view(),name="Accessory_list"),
	path('Merchandise/Accessory/<int:pk>/',AccessoryDetail.as_view(),name="Accessory_detail"),

	path('Merchandise/Gem/',GemList.as_view(),name="Gem_list"),
	path('Merchandise/Gem/<int:pk>/',GemDetail.as_view(),name="Gem_detail"),

	path('Merchandise/Gem/Pearl/',PearlList.as_view(),name="Pearl_list"),
	path('Merchandise/Gem/Pearl/<int:pk>/',PearlDetail.as_view(),name="Pearl_detail"),

	path('Merchandise/Gem/Diamond/',DiamondList.as_view(),name="Diamond_list"),
	path('Merchandise/Gem/Diamond/<int:pk>/',DiamondDetail.as_view(),name="Diamond_detail"),

	path('Merchandise/Gem/ColoredGem/',ColoredGemList.as_view(),name="ColoredGem_list"),
	path('Merchandise/Gem/ColoredGem/<int:pk>/',ColoredGemDetail.as_view(),name="ColoredGem_detail"),
]

TBS/jewelry/urls.py
from django.urls import path,re_path

from .views import JewelryListView,JewelListView,AccessoryListView,PearlListView,DiamondListView,ColoredGemListView,OtherListView



urlpatterns = [
	path('Merchandise/list/',JewelryListView.as_view(),name="merchandise_list"),
    path('Other/list/',OtherListView.as_view(),name="other_list"),
    path('Jewel/list/',JewelListView.as_view(),name="jewel_list"),
    path('Accessory/list/',AccessoryListView.as_view(),name="accessory_list"),
    path('Pearl/list/',PearlListView.as_view(),name="pearl_list"),
    path('Diamond/list/',DiamondListView.as_view(),name="diamond_list"),
    path('ColoredGem/list/',ColoredGemListView.as_view(),name="colored_gem_list"),
]

TBS/jewelry/models.py
# -*- coding: utf-8 -*-
from django.db import models
from datetime import date
from django.utils import timezone
from user.models import Person,Address,Customer
# Create your models here.


class Depot(models.Model):
	SUPPLIER = 'SL'
	WAREHOUSE = 'WH'
	RETAIL_STORE = 'ST'
	AGENT = 'AG'
	MAINTENANCE = 'MT'

	DEPOT_TYPE = [
		(SUPPLIER,'供应商'),
		(WAREHOUSE,'仓库'),
		(RETAIL_STORE,'直营店'),
		(AGENT,'代理商'),
		(MAINTENANCE,'维修厂'),
	]

	lable = models.CharField("名称",max_length=20)

	depot_type = models.CharField(max_length=2,choices=DEPOT_TYPE,blank=False,default=WAREHOUSE)
	contact = models.ForeignKey(
		Person,
		on_delete=models.SET_NULL,
		null=True,
		blank=True,
		related_name = "+",
		verbose_name = "联系人"
	)
	address = models.ForeignKey(
		Address,
		on_delete=models.SET_NULL,
		null=True,
		blank=True,
		related_name = "+",
		verbose_name = "地址"
	)
	
	def __str__(self):
		return self.lable
	class Meta:
		verbose_name = "场所"
		verbose_name_plural = verbose_name

'''
class MerchandiseManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)
'''

class Merchandise(models.Model):
	#filterout deleted objects
	#objects = MerchandiseManager()

	img = models.ImageField("图像",null=True, blank=True, upload_to="thumbnail/")

	description = models.CharField("描述",max_length = 50)
	net_weight = models.FloatField("净重",blank=True)

	sku = models.CharField(
		"款号",
		max_length = 20,
		help_text = "配对的两颗宝石拥有相同sku;"+
					"整包裸石拥有相同的sku;"+
					"套装成品拥有相同的sku;"+
					"同款多件拥有相同的sku。"
	)
	
	supplier = models.ForeignKey(
		Depot,
		on_delete=models.SET_NULL,
		null=True,
		blank=True,
		related_name = "supplies",
		verbose_name="供货商"
	)

	supply_date = models.DateTimeField("入库时间",default = timezone.now)
	sku_by_supplier = models.CharField("厂家款号",max_length=20,blank=True)
	
	cost = models.FloatField("成本")

	manufacture = models.CharField("产地",max_length=10,blank=True)
	
	depot = models.ForeignKey(
		Depot,
		on_delete=models.SET_NULL,
		null=True,
		related_name = "instock",
		verbose_name = "场所"
	)

	position = models.CharField("库柜",max_length=20,blank=True)

	price = models.FloatField("标价")
	margin = models.FloatField("价格浮动",blank=True,default=0)

	#deleted = models.BooleanField(default=False)
	def __str__(self):
		return self.description


class Certificate(models.Model):
	CERTIFICATE_BY=(
		("","N/A"),
		("NJC","中国国家首饰质量检验检测中心(NJC)"),
		("PSL","日本真珠科学研究所(PSL)"),
		("PEPCA","日本真珠输出加工协同组合(PEPCA)"),
		("PIC","日本真珠综合研究所(PIC)"),
		("GIA","美国宝石学院(GIA)"),
		("IGI","国际宝石学院(IGI)"),
		("AGS","美国宝石学会(AGS)"),
		("EGL","欧洲宝石学实验室(EGL)"),
	)
	issuer = models.CharField("颁发机构",max_length=5,default="",choices=CERTIFICATE_BY)
	code = models.CharField("证书编号",max_length=50,default="",blank=True)
	merchandise = models.ForeignKey(
		Merchandise,
		on_delete=models.CASCADE,
		blank=False,
		related_name = "certificate",
		verbose_name = "证书",
	)
	def __str__(self):
		return self.issuer+":"+code
	class Meta:
		verbose_name = "证书"
		verbose_name_plural = verbose_name
# chain or ring have size

class Jewel(Merchandise):
	JEWEL_TYPE = (
		("","N/A"),
		("R","戒指"),
		("项链",(
			("P","项坠"),
			("N","珠链"),
		)),
		("耳饰",(
			("D","耳钉"),
			("G","耳钩"),
			("X","耳线"),
			("J","耳夹"),
		)),
		("W","手链"),
		("B","胸针"),
		("H","头饰"),
	)
	
	jewel_type = models.CharField('类别',max_length=5,choices=JEWEL_TYPE,default="")
	style = models.CharField(
		"风格",
		max_length = 100,
		blank = True,
		default = "",
		help_text = "工艺或风格系列，例如花丝、满天星"
	)

	def __str__(self):
		return "成品"+self.description
	class Meta:
		verbose_name = "成品"
		verbose_name_plural = verbose_name
	


class Accessory(Merchandise):
	METAL_TYPE = (
		("PT","铂金"),
		("24KG","24K金"),
		("18KY","18K黄"),
		("18KW","18K白"),
		("18KR","18K红"),
		("14KY","14K黄"),
		("14KW","14K白"),
		("14KR","14K红"),
		("10KY","14K黄"),
		("10KW","14K白"),
		("10KR","14K红"),
		("SILV","纯银"),
		("S925","S925"),
		("GONB","铜镀金"),
		("ALLO","合金"),
		("","N/A")
	)
	metal_type = models.CharField(max_length=4,choices = METAL_TYPE,default="")
	belongs_to_jewel = models.ForeignKey(
		Jewel,
		null = True,
		blank = True,
		on_delete = models.SET_NULL,
		related_name = "accessory",
		verbose_name = "所属成品",
	)

	def __str__(self):
		return self.description
	class Meta:
		verbose_name = "配件"
		verbose_name_plural = verbose_name
	


class Gem(Merchandise):

	belongs_to_accessory = models.ForeignKey(
		Accessory,
		null = True,
		blank = True,
		on_delete=models.SET_NULL,
		related_name = "gem",
		verbose_name = "所属空托或配件",
		help_text = "如果是配石"
	)

	belongs_to_jewel = models.ForeignKey(
		Jewel,
		null = True,
		blank = True,
		on_delete = models.SET_NULL,
		related_name = "gem",
		verbose_name = "所属成品",
		help_text = "如果是主石"
	)

'''
size, 直径
shape, 形状
color, 颜色
luster, 光泽
surface, 表皮
nacre，珠层
'''
#大小 光泽 瑕疵 颜色
#圆珠 圆度（正圆，近圆，扁圆）
#水滴
#mabe
#巴洛克 keshi（无核）
class Pearl(Gem):
	PEARL_TYPE = (
		("","N/A"),
		("海水珍珠",(
				("AWHT","南洋白珍珠"),
				("SSGD","南洋金珍珠"),
				("TBLK","大溪地黑珍珠"),
				("AKOY","AKOYA"),
				("MABE","马贝珠"),
				("KESH","KESHI"),
				("CONC","海螺珠"),
			)
		),
		("淡水珍珠",(
				("FRWT","淡水珍珠"),
				("BARQ","巴洛克珍珠"),
				("EDSN","爱迪生珍珠"),
			)
		)
	)

	pearl_type = models.CharField(max_length=4,choices=PEARL_TYPE,default="")

	min_size = models.FloatField()
	max_size = models.FloatField()

	#color
	body_color = models.CharField("体色",max_length=10)
	overtone = models.CharField("伴色",max_length=10)
	IRIDESCENCE = (("","N/A"),("A","强"),("B","明显"),("C","一般"))
	iridescence = models.CharField("晕彩",max_length=1,choices=IRIDESCENCE,default="")

	LUSTER = (("","N/A"),("A","极强"),("B","强"),("C","中"),("D","弱"))
	luster = models.CharField("光泽",max_length=1,choices=LUSTER)

	SURFACE = (("","N/A"),("A","无瑕"),("B","微瑕"),("C","小瑕"),("D","瑕疵"),("E","重瑕"))
	surface = models.CharField("表皮",max_length=1,choices=SURFACE)

	NACRE = (("","N/A"),("A","特厚"),("B","厚"),("C","中"),("D","薄"),("E","极薄"))
	nacre = models.CharField("珠层",max_length=1,choices=NACRE)

	def __str__(self):
		return "珍珠"
	class Meta:
		verbose_name = "珍珠"
		verbose_name_plural = verbose_name

class Diamond(Gem):
	COLOR = (
		("","N/A"),
		("D","D"),
		("E","E"),
		("F","F"),
		("G","G"),
		("H","H"),
		("I","I"),
		("J","J"),
		("K","K"),
	)
	color = models.CharField("颜色",max_length=1,choices=COLOR,default="")

	CLARITY = (
		("","N/A"),
		("FL","FL"),
		("IF","IF"),
		("VVS1","VVS1"),
		("VVS2","VVS2"),
		("VS1","VS1"),
		("VS2","VS2"),
		("SI1","SI1"),
		("SI2","SI2"),
	)
	clarity = models.CharField("净度",max_length=4,choices=CLARITY,default="")

	CUT = (
		("","N/A"),
		("EX","EX"),
		("VG","VG"),
		("G","G"),
	)
	cut = models.CharField("切工",max_length=2,choices=CUT,default="")
	def __str__(self):
		return "钻石"+"{:.2f}".format(self.net_weight/0.2)+"ct"
	class Meta:
		verbose_name = "钻石"
		verbose_name_plural = verbose_name

class ColoredGem(Gem):
	def __str__(self):
		return "彩宝"
	class Meta:
		verbose_name = "彩宝"
		verbose_name_plural = verbose_name
		proxy = True


class PriceCategory(models.Model):
	description = models.CharField(max_length = 50)


#调货单
class Transfer(models.Model):
	datetime = models.DateTimeField("付款时间",default = timezone.now)
	merchandise = models.ManyToManyField(Merchandise)
	source = models.ForeignKey(
		Depot,
		on_delete=models.PROTECT,
		blank=False,
		related_name = "+",
	)
	destination = models.ForeignKey(
		Depot,
		on_delete=models.PROTECT,
		blank=False,
		related_name = "+",
	)

	def __str__(self):
		return source.lable+"->"+destination.lable+":"+str(merchandise.objects.count())

	class Meta:
		verbose_name = "调货单"
		verbose_name_plural = verbose_name


#借货单
class Lend(models.Model):
	pass

#加工单
class Maintain(models.Model):
	pass

#盘点单
class StockTake(models.Model):
	pass

TBS/jewelry/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm

from .models import Record,MerchandiseRecord,RecordPay


class RecordPayForm(ModelForm):
	class Meta:
		model = RecordPay
		exclude = ()

class MerchandiseRecordForm(ModelForm):
	class Meta:
		model = MerchandiseRecord
		exclude = ()

TBS/jewelry/api/views.py
from django.shortcuts import render

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics
from django.shortcuts import get_object_or_404

from jewelry.models import Depot
from jewelry.models import Certificate
from jewelry.models import PriceCategory
from jewelry.models import Record,MerchandiseRecord,RecordPay
from jewelry.models import Sku,Merchandise
from jewelry.models import Jewel
from jewelry.models import Gem,Pearl,Diamond,ColoredGem

from .serializers import DepotSerializer
from .serializers import CertificateSerializer
from .serializers import PriceCategorySerializer
from .serializers import RecordSerializer,MerchandiseRecordSerializer,RecordPaySerializer
from .serializers import SkuSerializer,MerchandiseSerializer
from .serializers import JewelSerializer,AccessorySerializer
from .serializers import GemSerializer,PearlSerializer,DiamondSerializer,ColoredGemSerializer
# Create your views here.

class DepotList(generics.ListCreateAPIView):
	queryset = Depot.objects.all()
	serializer_class = DepotSerializer

class DepotDetail(generics.RetrieveDestroyAPIView):
	queryset = Depot.objects.all()
	serializer_class = DepotSerializer

class CertificateList(generics.ListCreateAPIView):
	queryset = Certificate.objects.all()
	serializer_class = CertificateSerializer

class CertificateDetail(generics.RetrieveDestroyAPIView):
	queryset = Certificate.objects.all()
	serializer_class = CertificateSerializer

class PriceCategoryList(generics.ListCreateAPIView):
	queryset = PriceCategory.objects.all()
	serializer_class = PriceCategorySerializer

class PriceCategoryDetail(generics.RetrieveDestroyAPIView):
	queryset = PriceCategory.objects.all()
	serializer_class = PriceCategorySerializer

class RecordList(generics.ListCreateAPIView):
	queryset = Record.objects.all()
	serializer_class = RecordSerializer

class RecordDetail(generics.RetrieveDestroyAPIView):
	queryset = Record.objects.all()
	serializer_class = RecordSerializer

class MerchandiseRecordList(generics.ListCreateAPIView):
	queryset = MerchandiseRecord.objects.all()
	serializer_class = MerchandiseRecordSerializer

class MerchandiseRecordDetail(generics.RetrieveDestroyAPIView):
	queryset = MerchandiseRecord.objects.all()
	serializer_class = MerchandiseRecordSerializer

class RecordPayList(generics.ListCreateAPIView):
	queryset = RecordPay.objects.all()
	serializer_class = RecordPaySerializer

class RecordPayDetail(generics.RetrieveDestroyAPIView):
	queryset = RecordPay.objects.all()
	serializer_class = RecordPaySerializer

class SkuList(generics.ListCreateAPIView):
	queryset = Sku.objects.all()
	serializer_class = SkuSerializer

class SkuDetail(generics.RetrieveDestroyAPIView):
	queryset = Sku.objects.all()
	serializer_class = SkuSerializer

class MerchandiseList(generics.ListCreateAPIView):
	queryset = Merchandise.objects.all()
	serializer_class = MerchandiseSerializer

class MerchandiseDetail(generics.RetrieveDestroyAPIView):
	queryset = Merchandise.objects.all()
	serializer_class = MerchandiseSerializer

class JewelList(generics.ListCreateAPIView):
	queryset = Jewel.objects.all()
	serializer_class = JewelSerializer

class JewelDetail(generics.RetrieveDestroyAPIView):
	queryset = Jewel.objects.all()
	serializer_class = JewelSerializer

class AccessoryList(generics.ListCreateAPIView):
	queryset = Jewel.objects.all()
	serializer_class = AccessorySerializer

class AccessoryDetail(generics.RetrieveDestroyAPIView):
	queryset = Jewel.objects.all()
	serializer_class = AccessorySerializer

class GemList(generics.ListCreateAPIView):
	queryset = Gem.objects.all()
	serializer_class = GemSerializer

class GemDetail(generics.RetrieveDestroyAPIView):
	queryset = Gem.objects.all()
	serializer_class = GemSerializer

class PearlList(generics.ListCreateAPIView):
	queryset = Pearl.objects.all()
	serializer_class = PearlSerializer

class PearlDetail(generics.RetrieveDestroyAPIView):
	queryset = Pearl.objects.all()
	serializer_class = PearlSerializer

class DiamondList(generics.ListCreateAPIView):
	queryset = Diamond.objects.all()
	serializer_class = DiamondSerializer

class DiamondDetail(generics.RetrieveDestroyAPIView):
	queryset = Diamond.objects.all()
	serializer_class = DiamondSerializer

class ColoredGemList(generics.ListCreateAPIView):
	queryset = ColoredGem.objects.all()
	serializer_class = ColoredGemSerializer

class ColoredGemDetail(generics.RetrieveDestroyAPIView):
	queryset = ColoredGem.objects.all()
	serializer_class = ColoredGemSerializer

TBS/templates/jewelry/accessory_list.html
{% extends "base.html" %}

{% block title %}成品列表{% endblock %}

{% block nav-tabs %}
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'merchandise_list' %}">所有</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'jewel_list' %}">成品</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'accessory_list' %}">配件</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'pearl_list' %}">裸珠</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'diamond_list' %}">钻石</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'colored_gem_list' %}">彩宝</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'other_list' %}">其它</a>
    </li>

  </ul>
{% endblock %}

{% block content %} 


<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">缩略图</th>
      <th scope="col">#</th>
      <th scope="col">描述</th>
      <th scope="col">位置</th>
      <th scope="col">类型</th>
      <th scope="col">价格类别</th>
      <th scope="col">价格</th>
    </tr>
  </thead>
  <tbody>
    {% for merchandise in merchandises %}


    <tr valign="middle">
      <td>
        <img class="img-thumbnail rounded shadow" src='{{merchandise.img.url}}' width="70" serialId={{merchandise.serialId|upper}} description={{merchandise.description|truncatewords:"20"}}>
      </td>
      <th scope="row">{{merchandise.serialId|upper}}</th>
      <td>{{merchandise.description|truncatewords:"20"}}</td>
      <td>{{merchandise.depot}}</td>
      <td>{{merchandise.get_jewel_type_display}}</td>
      <td>{{merchandise.price_category}}</td>
      <td>{{merchandise.price}}</td>
    </tr>

    {% endfor %}
  </tbody>
</table>

{% include "paginator.html" with page_obj="merchandises" %}


<script>
  $(".img-thumbnail").click(
    function() {
      $('.imagepreview').attr('src', $(this).attr('src'));
      $('#imagepreview_detail').html($(this).attr('serialId')+"<br>"+$(this).attr('description'))
      $('#imagemodal').modal('show'); 
    }
    )

  </script>

  <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" data-dismiss="modal">
      <div class="modal-content"  >              
        <div class="modal-body">
         <img src="" class="imagepreview" style="width: 100%;" >
       </div> 
       <div class="modal-footer">
         <div class="col-xs-12">
           <p class="text-left" id="imagepreview_detail" align="right">1. line of description<br>2. line of description <br>3. line of description</p>
         </div>
       </div>         
     </div>
   </div>
 </div>

{% endblock %}

{% block side1%}

<form method="get">

       {{ filter.form.as_p }}


      <div class="d-grid gap-2 col-8 mx-auto">
        <div class="btn-group" role="group">
          <a href="{{ request.path }}">
          <button type="button" class="btn btn-outline-primary btn-sm" >重置</button>
          </a>
          <input class="btn btn-primary btn-sm" type="submit" value="过滤" />
        </div>
      </div>
</form>


{%endblock%}

TBS/templates/jewelry/colored_gem_list.html
{% extends "base.html" %}

{% block title %}成品列表{% endblock %}

{% block nav-tabs %}
 <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'merchandise_list' %}">所有</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'jewel_list' %}">成品</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accessory_list' %}">配件</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'pearl_list' %}">裸珠</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'diamond_list' %}">钻石</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'colored_gem_list' %}">彩宝</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'other_list' %}">其它</a>
    </li>

  </ul>
{% endblock %}

{% block content %} 


<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">缩略图</th>
      <th scope="col">#</th>
      <th scope="col">描述</th>
      <th scope="col">位置</th>
      <th scope="col">类型</th>
      <th scope="col">价格类别</th>
      <th scope="col">价格</th>
    </tr>
  </thead>
  <tbody>
    {% for merchandise in merchandises %}


    <tr valign="middle">
      <td>
        <img class="img-thumbnail rounded shadow" src='{{merchandise.img.url}}' width="70" serialId={{merchandise.serialId|upper}} description={{merchandise.description|truncatewords:"20"}}>
      </td>
      <th scope="row">{{merchandise.serialId|upper}}</th>
      <td>{{merchandise.description|truncatewords:"20"}}</td>
      <td>{{merchandise.depot}}</td>
      <td>{{merchandise.get_jewel_type_display}}</td>
      <td>{{merchandise.price_category}}</td>
      <td>{{merchandise.price}}</td>
    </tr>

    {% endfor %}
  </tbody>
</table>

{% include "paginator.html" with page_obj="merchandises" %}


<script>
  $(".img-thumbnail").click(
    function() {
      $('.imagepreview').attr('src', $(this).attr('src'));
      $('#imagepreview_detail').html($(this).attr('serialId')+"<br>"+$(this).attr('description'))
      $('#imagemodal').modal('show'); 
    }
    )

  </script>

  <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" data-dismiss="modal">
      <div class="modal-content"  >              
        <div class="modal-body">
         <img src="" class="imagepreview" style="width: 100%;" >
       </div> 
       <div class="modal-footer">
         <div class="col-xs-12">
           <p class="text-left" id="imagepreview_detail" align="right">1. line of description<br>2. line of description <br>3. line of description</p>
         </div>
       </div>         
     </div>
   </div>
 </div>

{% endblock %}

{% block side1%}

<form method="get">

       {{ filter.form.as_p }}


      <div class="d-grid gap-2 col-8 mx-auto">
        <div class="btn-group" role="group">
          <a href="{{ request.path }}">
          <button type="button" class="btn btn-outline-primary btn-sm" >重置</button>
          </a>
          <input class="btn btn-primary btn-sm" type="submit" value="过滤" />
        </div>
      </div>
</form>


{%endblock%}